{{- if .Values.thanos.compactor.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compactor
  namespace: {{ .Values.namespace }}
  labels:
    app: thanos-compactor
spec:
  serviceName: thanos-compactor
  replicas: {{ .Values.thanos.compactor.replicas }}
  selector:
    matchLabels:
      app: thanos-compactor
      thanos-store-api: "true"
  template:
    metadata:
      labels:
        app: thanos-compactor
        thanos-store-api: "true"
    spec:
      containers:
        - name: thanos
          image: {{ .Values.thanos.image }}
          args:
            - compact
            - --log.level=debug
            - --data-dir=/data
            - --retention.resolution-raw=15d
            - --retention.resolution-5m=10d
            - --retention.resolution-1h=10d
            - "--objstore.config={type: AWS, config: {bucket: {{.Values.thanos.archive_bucket}} }}"
            - --wait
          env:
            - name : AWS_APPLICATION_CREDENTIALS
              value: /etc/secret/thanos-aws-credentials.json
          ports:
            - name: http
              containerPort: 10902
          livenessProbe:
            httpGet:
              port: http
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
          resources:
            {{- toYaml .Values.thanos.compactor.resources | nindent 12 }}
          volumeMounts:
            - name: thanos-aws-credentials
              mountPath: /etc/secret
              readOnly: false
      volumes:
        - name: thanos-aws-credentials
          secret:
            secretName: {{ .Values.thanos.aws_secret }}
{{- end }}
